version: 0.2

phases:
  install:
    commands:
      - echo "Install dependencies"
      - npm ci
  build:
    commands:
      - echo "Build step (if any)"
      - npm run build || echo "No build script, continuing"
artifacts:
  files:
    - '**/*'
  discard-paths: no
